name: "Check CML GitHub Action"

on: [push, workflow_dispatch]

jobs:
  check:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        runs-on: [ '{"runs-on": "ubuntu-latest"}', 
          '{"runs-on": "macos-latest"}', 
          '{"runs-on": "ubuntu-latest", "container": "ubuntu:18.04"}', 
          '{"runs-on": "windows-latest"}']

    runs-on: ${{ fromJSON(matrix.runs-on).runs-on }}
    container: ${{ fromJSON(matrix.runs-on).container }} 

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        if: "fromJSON(matrix.runs-on).container == 'ubuntu:18.04' 
          || contains(fromJSON(matrix.runs-on).runs-on, 'windows')"
        with:
          node-version: '12'
    
      - uses: 0x2b3bfa0/setup-cml@v1

  
