name: "Check CML GitHub Action"

on: [push, workflow_dispatch]

jobs:
  check:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]

    runs-on: ${{ fromJSON(matrix.runs-on).runs-on }}
    container: ${{ fromJSON(matrix.runs-on).container }} 

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
    
      - uses: 0x2b3bfa0/setup-cml@v1

  
