name: "Check CML GitHub Action"

on: [push, workflow_dispatch]

jobs:
  check:
   
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
    
      - uses: 0x2b3bfa0/setup-cml@v1

  
